### ISSUE TITLE
Problem via `NPM install ` setup

### ISSUE THREAD

**Issue by DSoftwareArtist** [bitjson/qr-code#2]
installing this package using `npm install @bitjson/qr-code`  and importing this way don't worked:

```
<script src="/node_modules/@bitjson/qr-code/dist/qr-code.js"></script>
<script src="/node_modules/@bitjson/qr-code/dist/qr-code/qr-code.orxjfzvr.js" type="module" crossorigin="true" data-resources-url="/node_modules/@bitjson/qr-code/dist/qr-code/" data-namespace="qr-code"></script>
```

### Or even importing this way:

```
<script src="/node_modules/@bitjson/qr-code/dist/qr-code.js"></script>
```

I personally don't want to use `CDN` because I want to load the script from local storage.

I have the feeling that the package installed during `npm install` is not updated. Please help me on this.

**Comment by Roba1993** [comment]
I'm facing the same problem. Is there any fix?

**Comment by chajnetajaroslaw** [comment]
Import it as: 

```js
import * as qr from "@bitjson/qr-code";
```

then run **defineCustomElements** with **window** as parameter, now you can use **<qr-code>** component. some parameters will be autocompleted incorrectly in IDE eg. position-ring-color as PositionRingColor, position-center-color as PositionCenterColor.

```js
qr.defineCustomElements(window);

<qr-code contents="https://bitjson.com"></qr-code>
```

[Stackblitz](https://stackblitz.com/edit/vitejs-vite-b23qfr?file=main.js)
